[
    {
        "@timestamp": "2016-10-25T14:49:34.000-02:00",
        "event.category": [
            "web"
        ],
        "event.dataset": "nginx.error",
        "event.kind": "event",
        "event.module": "nginx",
        "event.original": "2016/10/25 14:49:34 [error] 54053#0: *1 open() \"/usr/local/Cellar/nginx/1.10.2_1/html/favicon.ico\" failed (2: No such file or directory), client: 127.0.0.1, server: localhost, request: \"GET /favicon.ico HTTP/1.1\", host: \"localhost:8080\", referrer: \"http://localhost:8080/\"",
        "event.timezone": "-02:00",
        "event.type": [
            "error"
        ],
        "fileset.name": "error",
        "input.type": "log",
        "log.level": "error",
        "log.offset": 0,
        "message": "open() \"/usr/local/Cellar/nginx/1.10.2_1/html/favicon.ico\" failed (2: No such file or directory), client: 127.0.0.1, server: localhost, request: \"GET /favicon.ico HTTP/1.1\", host: \"localhost:8080\", referrer: \"http://localhost:8080/\"",
        "nginx.error.connection_id": 1,
        "process.pid": 54053,
        "process.thread.id": 0,
        "service.type": "nginx"
    },
    {
        "@timestamp": "2016-10-25T14:50:44.000-02:00",
        "event.category": [
            "web"
        ],
        "event.dataset": "nginx.error",
        "event.kind": "event",
        "event.module": "nginx",
        "event.original": "2016/10/25 14:50:44 [error] 54053#0: *3 open() \"/usr/local/Cellar/nginx/1.10.2_1/html/adsasd\" failed (2: No such file or directory), client: 127.0.0.1, server: localhost, request: \"GET /adsasd HTTP/1.1\", host: \"localhost:8080\"",
        "event.timezone": "-02:00",
        "event.type": [
            "error"
        ],
        "fileset.name": "error",
        "input.type": "log",
        "log.level": "error",
        "log.offset": 273,
        "message": "open() \"/usr/local/Cellar/nginx/1.10.2_1/html/adsasd\" failed (2: No such file or directory), client: 127.0.0.1, server: localhost, request: \"GET /adsasd HTTP/1.1\", host: \"localhost:8080\"",
        "nginx.error.connection_id": 3,
        "process.pid": 54053,
        "process.thread.id": 0,
        "service.type": "nginx"
    },
    {
        "@timestamp": "2019-10-30T23:26:34.000-02:00",
        "event.category": [
            "web"
        ],
        "event.dataset": "nginx.error",
        "event.kind": "event",
        "event.module": "nginx",
        "event.original": "2019/10/30 23:26:34 [error] 205860#205860: *180289 FastCGI sent in stderr: \"PHP message: PHP Warning:  Declaration of FEE_Field_Terms::wrap($content, $taxonomy, $before, $sep, $after) should be compatible with FEE_Field_Post::wrap($content, $post_id = 0) in /var/www/xxx/web/wp-content/plugins/front-end-editor/php/fields/post.php on line 0\nPHP message: PHP Warning:  Declaration of FEE_Field_Tags::wrap($content, $before, $sep, $after) should be compatible with FEE_Field_Terms::wrap($content, $taxonomy, $before, $sep, $after) in /var/www/xxx/web/wp-content/plugins/front-end-editor/php/fields/post.php on line 0\nPHP message: PHP Warning:  Declaration of FEE_Field_Category::wrap($content, $sep, $parents) should be compatible with FEE_Field_Terms::wrap($content, $taxonomy, $before, $sep, $after) in /var/www/xxx/web/wp-content/plugins/front-end-editor/php/fields/post.php on line 0",
        "event.timezone": "-02:00",
        "event.type": [
            "error"
        ],
        "fileset.name": "error",
        "input.type": "log",
        "log.flags": [
            "multiline"
        ],
        "log.level": "error",
        "log.offset": 500,
        "message": "FastCGI sent in stderr: \"PHP message: PHP Warning:  Declaration of FEE_Field_Terms::wrap($content, $taxonomy, $before, $sep, $after) should be compatible with FEE_Field_Post::wrap($content, $post_id = 0) in /var/www/xxx/web/wp-content/plugins/front-end-editor/php/fields/post.php on line 0\nPHP message: PHP Warning:  Declaration of FEE_Field_Tags::wrap($content, $before, $sep, $after) should be compatible with FEE_Field_Terms::wrap($content, $taxonomy, $before, $sep, $after) in /var/www/xxx/web/wp-content/plugins/front-end-editor/php/fields/post.php on line 0\nPHP message: PHP Warning:  Declaration of FEE_Field_Category::wrap($content, $sep, $parents) should be compatible with FEE_Field_Terms::wrap($content, $taxonomy, $before, $sep, $after) in /var/www/xxx/web/wp-content/plugins/front-end-editor/php/fields/post.php on line 0",
        "nginx.error.connection_id": 180289,
        "process.pid": 205860,
        "process.thread.id": 205860,
        "service.type": "nginx"
    },
    {
        "@timestamp": "2019-11-05T14:50:44.000-02:00",
        "event.category": [
            "web"
        ],
        "event.dataset": "nginx.error",
        "event.kind": "event",
        "event.module": "nginx",
        "event.original": "2019/11/05 14:50:44 [error] 54053#0: *3 open() \"/usr/local/Cellar/nginx/1.10.2_1/html/adsasd\" failed (2: No such file or directory), client: 127.0.0.1, server: localhost, request: \"GET /pysio HTTP/1.1\", host: \"localhost:8080\"",
        "event.timezone": "-02:00",
        "event.type": [
            "error"
        ],
        "fileset.name": "error",
        "input.type": "log",
        "log.level": "error",
        "log.offset": 1386,
        "message": "open() \"/usr/local/Cellar/nginx/1.10.2_1/html/adsasd\" failed (2: No such file or directory), client: 127.0.0.1, server: localhost, request: \"GET /pysio HTTP/1.1\", host: \"localhost:8080\"",
        "nginx.error.connection_id": 3,
        "process.pid": 54053,
        "process.thread.id": 0,
        "service.type": "nginx"
    },
    {
        "@timestamp": "2023-02-28T17:19:15.000-02:00",
        "event.category": [
            "authententication",
            "web"
        ],
        "event.dataset": "nginx.error",
        "event.kind": "event",
        "event.module": "nginx",
        "event.original": "2023/02/28 17:19:15 [error] 677#677: *307 user \"sherlock\" was not found in \"/etc/nginx/access/test.com/htpasswd\", client: 10.10.10.10, server: _, request: \"GET / HTTP/2.0\", host: \"11.11.11.11\"",
        "event.outcome": "failure",
        "event.timezone": "-02:00",
        "event.type": [
            "error",
            "logon-failed"
        ],
        "fileset.name": "error",
        "http.request.method": "GET",
        "http.version": "2.0",
        "input.type": "log",
        "log.level": "error",
        "log.offset": 1612,
        "message": "user \"sherlock\" was not found in \"/etc/nginx/access/test.com/htpasswd\", client: 10.10.10.10, server: _, request: \"GET / HTTP/2.0\", host: \"11.11.11.11\"",
        "nginx.error.connection_id": 307,
        "process.pid": 677,
        "process.thread.id": 677,
        "related.ip": [
            "10.10.10.10"
        ],
        "related.user": [
            "sherlock"
        ],
        "service.type": "nginx",
        "source.ip": "10.10.10.10",
        "url.original": "/",
        "url.path": "/",
        "user.name": "sherlock"
    },
    {
        "@timestamp": "2023-02-28T17:24:54.000-02:00",
        "event.category": [
            "authententication",
            "web"
        ],
        "event.dataset": "nginx.error",
        "event.kind": "event",
        "event.module": "nginx",
        "event.original": "2023/02/28 17:24:54 [error] 9447#9447: *25049019 user \"sherlock\": password mismatch, client: 10.10.10.10, server: www.test.com, request: \"GET /mobile/test/?promoId=testNewSite2 HTTP/2.0\", host: \"www.test.com\", referrer: \"https://www.test.com/\"",
        "event.outcome": "failure",
        "event.timezone": "-02:00",
        "event.type": [
            "error",
            "logon-failed"
        ],
        "fileset.name": "error",
        "http.request.method": "GET",
        "http.request.referrer": "https://www.test.com/",
        "http.version": "2.0",
        "input.type": "log",
        "log.level": "error",
        "log.offset": 1805,
        "message": "user \"sherlock\": password mismatch, client: 10.10.10.10, server: www.test.com, request: \"GET /mobile/test/?promoId=testNewSite2 HTTP/2.0\", host: \"www.test.com\", referrer: \"https://www.test.com/\"",
        "nginx.error.connection_id": 25049019,
        "process.pid": 9447,
        "process.thread.id": 9447,
        "related.ip": [
            "10.10.10.10"
        ],
        "related.user": [
            "sherlock"
        ],
        "service.type": "nginx",
        "source.ip": "10.10.10.10",
        "url.original": "/mobile/test/?promoId=testNewSite2",
        "url.path": "/mobile/test/",
        "url.query": "promoId=testNewSite2",
        "user.name": "sherlock"
    }
]
